theme: jekyll-theme-slate
logo: '/assets/cazy_web_logo.svg'
title: Supplementary Inforamation -- Hobbs et al., 2023, cazy-webscraper
description: Supplementary inforamtion, scripts and data files presented in the manuscript Hobbs et al.
